version: '3'

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    user: postgres
    ports:
      - "5432:5432"
  
  backend:
    image: node:lts-alpine3.13
    container_name: backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend
    working_dir: /backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    entrypoint: >
      sh -c "npm install
      && npm run start:dev"
  
  frontend:
    image: node:lts-alpine3.13
    container_name: frontend
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    entrypoint: >
      sh -c "npm install
      && npm start"
      