services:
  # nestjs:
  #   build: ./nestjs-toy/
  #   ports:
  #     - "3000:3000"
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_INITDB_ARGS: ""
      POSTGRES_INITDB_WALDIR: ""
      POSTGRES_HOST_AUTH_METHOD: ""
    volumes:
      # - ./initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "database"
      DB_PORT: "${DB_PORT}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      FT_CLIENT_ID: "${FT_CLIENT_ID}"
      FT_CLIENT_SECRET: "${FT_CLIENT_SECRET}"
      FT_CALLBACK: "${FT_CALLBACK}"
      JWT_SECRET: "${JWT_SECRET}"
      SESSION_SECRET: "${SESSION_SECRET}"
      CLIENT_ADDRESS: "${CLIENT_ADDRESS}"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_42_CLIENT_ID: ${REACT_APP_42_CLIENT_ID}
      REACT_APP_42_CLIENT_SECRET: ${REACT_APP_42_CLIENT_SECRET}
      REACT_APP_42_CALLBACK: ${REACT_APP_42_CALLBACK}
      REACT_APP_SERVER_ADDRESS: ${REACT_APP_SERVER_ADDRESS}
      REACT_APP_SOCKET_ADDRESS: ${REACT_APP_SOCKET_ADDRESS}

volumes:
  db_data: